FROM eclipse-temurin:17-jdk

WORKDIR /app

# Копируем ВСЕ включая библиотеки
COPY . .

# Создаем необходимые папки
RUN mkdir -p logs

# Компилируем проект ВНУТРИ контейнера
RUN javac -cp "lib/*" Main.java core/*.java scanners/*.java scanners/owasp/*.java scanners/DeepAnalyzer/*.java gost/*.java

# Открываем порт для веб-интерфейса
EXPOSE 8081

# Запускаем приложение
CMD ["java", "-cp", ".:lib/*", "Main"]
